#!/usr/bin/env python3
"""
Batch visualization runner for FLPQ parsing algorithms.

Runs specified algorithms via the FLPQ CLI, collects all DOT and TeX output,
compiles DOT graphs to PDFs, and merges all TeX fragments into a single
compilable TeX document with step-by-step visualization.

Usage:
    python3 run_viz.py [--algorithms CYK Valiant] [--grammar grammar.bnf]
                       [--input input.txt] [--output ./viz_output]
                       [--example]

    --example       Generate example PDFs for CYK and Valiant on grammar
                    S -> S S | eps | a S b with input "a a b a b b"
"""

import argparse
import os
import subprocess
import sys
import shutil
import tempfile
from pathlib import Path

TEX_TEMPLATE = r"""\documentclass[12pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage[russian,english]{babel}
\usepackage{nicematrix}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage[margin=1cm,landscape]{geometry}
\usepackage{hyperref}
\usepackage{graphicx}

\title{FLPQ Parsing Visualization\\Algorithm: __ALGORITHM__}
\author{Generated by FLPQ Visualization Script}
\date{}

\begin{document}
\maketitle
\tableofcontents

__CONTENT__

\end{document}
"""

EXAMPLE_GRAMMAR = r"""S -> S S
S -> eps
S -> a S b"""

EXAMPLE_INPUT = "a a b a b b"

CLI_PROJECT = "src/FLPQ.Cli/FLPQ.Cli.fsproj"
REPO_ROOT = Path(__file__).resolve().parent


def find_repo_root():
    p = REPO_ROOT
    while p != p.parent:
        if (p / CLI_PROJECT).exists():
            return p
        p = p.parent
    return REPO_ROOT


def run_command(cmd, cwd=None, check_stderr=True):
    """Run a command and return success flag."""
    try:
        result = subprocess.run(
            cmd, cwd=cwd, capture_output=True, text=True, timeout=120
        )
        if result.returncode != 0:
            err = result.stderr[:500] if check_stderr else result.stdout[-1000:]
            print(f"  WARNING: {' '.join(cmd)} returned {result.returncode}", file=sys.stderr)
            if err:
                print(f"  details: {err}", file=sys.stderr)
            return False
        return True
    except Exception as e:
        print(f"  FAILED: {' '.join(cmd)}: {e}", file=sys.stderr)
        return False


def run_algorithm(algorithm, grammar_file, input_file, output_dir, repo_root):
    """Run the FLPQ CLI for one algorithm."""
    print(f"\n=== Running {algorithm} ===")
    cmd = [
        "dotnet", "run",
        "--project", str(repo_root / CLI_PROJECT),
        "-c", "Release",
        "--",
        "-a", algorithm,
        "-g", grammar_file,
        "-i", input_file,
        "-o", output_dir,
    ]
    print(f"  {' '.join(cmd)}")
    run_command(cmd, cwd=repo_root)


def compile_dot_to_pdf(dot_path, pdf_path):
    """Compile a DOT file to PDF using graphviz."""
    return run_command(["dot", "-Tpdf", "-o", str(pdf_path), str(dot_path)])


def compile_tex_to_pdf(tex_path, out_dir):
    """Compile a TeX file to PDF using pdflatex."""
    return run_command([
        "pdflatex",
        "-interaction=nonstopmode",
        "-output-directory", str(out_dir),
        str(tex_path),
    ])


def natural_sort_key(path):
    """Sort step_N directories naturally by number."""
    import re
    m = re.search(r'step_(\d+)', str(path))
    return int(m.group(1)) if m else 0


def collect_steps(viz_dir):
    """Collect all step directories sorted numerically."""
    step_dirs = sorted(
        [d for d in Path(viz_dir).iterdir() if d.is_dir()],
        key=natural_sort_key,
    )
    return step_dirs


def process_algorithm(algorithm, viz_dir, result_dir, repo_root):
    """Process one algorithm's output: compile DOT→PDF, build merged TeX."""
    step_dirs = collect_steps(viz_dir)
    if not step_dirs:
        print(f"  No steps found for {algorithm}")
        return

    algo_dir = result_dir / algorithm.lower()
    dot_pdf_dir = algo_dir / "dot_pdfs"
    dot_pdf_dir.mkdir(parents=True, exist_ok=True)

    tex_source = []
    tex_source.append(r"\section*{Algorithm: " + algorithm + r"}")
    tex_source.append(
        r"\textit{Total steps: " + str(len(step_dirs)) + r"}\\"
    )

    for step_dir in step_dirs:
        step_name = step_dir.name
        step_num = step_name.split("_")[1]

        tex_source.append(r"\subsection*{Step " + step_num + r"}")

        # Collect DOT files
        dot_files = list(step_dir.glob("*.dot"))
        for dot_file in sorted(dot_files):
            dot_name = dot_file.stem
            pdf_path = dot_pdf_dir / f"step_{step_num}_{dot_name}.pdf"
            if compile_dot_to_pdf(dot_file, pdf_path):
                tex_source.append(
                    r"\begin{center}"
                    r"\includegraphics[width=0.9\textwidth,keepaspectratio]{{"
                    + str(pdf_path.relative_to(algo_dir).as_posix())
                    + r"}}"
                    r"\end{center}"
                )
                tex_source.append("")

        # Collect TeX files
        tex_files = list(step_dir.glob("*.tex"))
        for tex_file in sorted(tex_files):
            content = tex_file.read_text(encoding="utf-8")
            tex_source.append(r"\begin{center}")
            tex_source.append(r"\[")
            tex_source.append(content.strip())
            tex_source.append(r"\]")
            tex_source.append(r"\end{center}")
            tex_source.append("")

    # Write merged TeX
    merged_tex = algo_dir / f"{algorithm.lower()}_merged.tex"
    content_text = "\n".join(tex_source)
    full_tex = TEX_TEMPLATE.replace("__ALGORITHM__", algorithm)
    full_tex = full_tex.replace("__CONTENT__", content_text)
    merged_tex.write_text(full_tex, encoding="utf-8")

    print(f"  Merged TeX: {merged_tex}")

    # Compile merged TeX to PDF (run twice for cross-references)
    out_dir = algo_dir / "merged_tex_build"
    out_dir.mkdir(exist_ok=True)

    build_tex = out_dir / f"{algorithm.lower()}_merged.tex"
    shutil.copy(merged_tex, build_tex)
    compile_tex_to_pdf(build_tex, out_dir)
    compile_tex_to_pdf(build_tex, out_dir)  # Second pass for ToC and references

    merged_pdf = out_dir / f"{algorithm.lower()}_merged.pdf"
    if merged_pdf.exists():
        final_pdf = algo_dir / f"{algorithm.lower()}_visualization.pdf"
        shutil.copy(merged_pdf, final_pdf)
        print(f"  Final PDF: {final_pdf}")
    else:
        print(f"  WARNING: PDF compilation failed for {algorithm}")
        log = out_dir / f"{algorithm.lower()}_merged.log"
        if log.exists():
            errors = [
                line for line in log.read_text().splitlines()
                if line.startswith("!")
            ]
            if errors:
                print("  TeX errors found:")
                for e in errors[:10]:
                    print(f"    {e}")


def main():
    parser = argparse.ArgumentParser(
        description="FLPQ Batch Visualization Runner"
    )
    parser.add_argument(
        "--algorithms", nargs="+",
        default=["CYK", "Valiant", "LL", "LR"],
        choices=["CYK", "Valiant", "LL", "LR"],
        help="Algorithms to run (default: all)"
    )
    parser.add_argument(
        "--grammar", default=None,
        help="Path to grammar file (.bnf)"
    )
    parser.add_argument(
        "--input", default=None,
        help="Path to input string file"
    )
    parser.add_argument(
        "--output", default="./viz_output",
        help="Output directory (default: ./viz_output)"
    )
    parser.add_argument(
        "--example", action="store_true",
        help="Run example: CYK + Valiant on S->SS|eps|aSb with input aababb"
    )

    args = parser.parse_args()

    repo_root = find_repo_root()

    if args.example:
        tmpdir = tempfile.mkdtemp(prefix="flpq_example_")
        grammar_file = os.path.join(tmpdir, "grammar.bnf")
        input_file = os.path.join(tmpdir, "input.txt")
        Path(grammar_file).write_text(EXAMPLE_GRAMMAR)
        Path(input_file).write_text(EXAMPLE_INPUT)
        algorithms = ["CYK", "Valiant"]
        output_dir = args.output
        print(f"Grammar: S -> S S | eps | a S b")
        print(f"Input:   a a b a b b")
    else:
        if not args.grammar or not args.input:
            parser.error("--grammar and --input required unless --example is used")
        grammar_file = os.path.abspath(args.grammar)
        input_file = os.path.abspath(args.input)
        algorithms = args.algorithms
        output_dir = args.output

    output_dir = os.path.abspath(output_dir)
    result_dir = Path(output_dir) / "results"
    result_dir.mkdir(parents=True, exist_ok=True)

    print(f"Output directory: {output_dir}")
    print(f"Algorithms: {algorithms}")
    print(f"Grammar: {grammar_file}")
    print(f"Input: {input_file}")

    for algorithm in algorithms:
        viz_dir = Path(output_dir) / f"{algorithm.lower()}_steps"
        run_algorithm(algorithm, grammar_file, input_file, str(viz_dir), repo_root)
        process_algorithm(algorithm, str(viz_dir), result_dir, repo_root)

    print(f"\nDone. Results in {result_dir}/")

    # Show summary
    for algorithm in algorithms:
        pdf = result_dir / algorithm.lower() / f"{algorithm.lower()}_visualization.pdf"
        if pdf.exists():
            print(f"  {algorithm}: {pdf}")


if __name__ == "__main__":
    main()
