<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Generators.fs" />
    <Compile Include="LanguageRegistry.fs" />
    <Compile Include="TestHelpers.fs" />
    <Compile Include="ParsingTestCases.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck.Xunit" Version="3.3.3" />
    <PackageReference Include="FSharpPlus" Version="1.9.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FLPQ.Languages\FLPQ.Languages.fsproj" />
    <ProjectReference Include="..\..\src\FLPQ.LinearAlgebra\FLPQ.LinearAlgebra.fsproj" />
    <ProjectReference Include="..\..\src\FLPQ.GraphAnalysis\FLPQ.GraphAnalysis.fsproj" />
    <ProjectReference Include="..\..\src\FLPQ.RPQ\FLPQ.RPQ.fsproj" />
  </ItemGroup>

</Project>
