<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AlgorithmTypes.fs" />
    <Compile Include="Helpers.fs" />
    <Compile Include="CykRunner.fs" />
    <Compile Include="ValiantRunner.fs" />
    <Compile Include="LLRunner.fs" />
    <Compile Include="LRRunner.fs" />
    <Compile Include="GllRunner.fs" />
    <Compile Include="RnglrRunner.fs" />
    <Compile Include="Summary.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FLPQ.Languages\FLPQ.Languages.fsproj" />
    <ProjectReference Include="..\FLPQ.Printers\FLPQ.Printers.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Argu" Version="6.2.5" />
    <PackageReference Include="FSharpPlus" Version="1.9.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\data\tex_summary_template.tex">
      <Link>tex_summary_template.tex</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
